# Generated by Django 5.0.6 on 2024-06-23 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(max_length=100, null=True, verbose_name={('female', 'Female'), ('male', 'Male'), ('others', 'Others')}),
        ),
        migrations.CreateModel(
            name='calorieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
