# Generated by Django 5.0.6 on 2024-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieApp', '0002_custom_user_gender_calorieinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('others', 'Others'), ('male', 'Male')], max_length=100, null=True),
        ),
    ]
