# Generated by Django 5.0.6 on 2024-06-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieApp', '0006_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
    ]
