# Generated by Django 5.0.6 on 2024-06-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorieApp', '0008_alter_custom_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='consume',
            field=models.IntegerField(null=True),
        ),
    ]
